export const metadata = {
  title: "PKS Web Site",
  description: "Generated by pks",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <nav>네브바</nav>
        {children}
      </body>
    </html>
  );
}
